### ISSUE TITLE
Smartapps full and lite can't be installed because of syntax error

### ISSUE THREAD

**Issue by AlbertoZen** [sgupta999/mqtt-bridge-smartthings#15]
In the full smartapp (I haven't tried the lite yet), smartthings IDE doesn't let install or copy the smartapp because of a missing comma in actionOpenClosed

    "contactSensors": [
        name: "Contact Sensor",
        capability: "capability.contactSensor",
        attributes: [
            "contact"
        ]**,**
        action: "actionOpenClosed"

**Comment by sgupta999** [comment]
sorry about that - i mostly use the lite version.
Nice catch - Updated the file on github thanks
