### ISSUE TITLE
Can't save ip/port/mac in SmartThings IDE

### ISSUE THREAD

**Issue by AlexDanault** [sgupta999/mqtt-bridge-smartthings#20]
Hi !

No matter how many times I tried, I always get stuck at the same step : After installing the device handler and creating a device for it, I can't set the IP/port/mac of the MBS server that is running on my PC, I always the this error on saving:

```
Oh No! Something Went Wrong!

Error
    500: Internal Server Error
URI
    /device/list
Reference Id
    142a3cf6-53e6-459b-9fb0-c5ea7e5ed7b6
Date
    Mon Feb 17 01:54:30 UTC 2020
```

I confirmed that my server is running (and http on port 8080 is accessible) so I'm not sure where the problem is. It seems SmartThings really hates something I do because at this point the device and smartapp are completely frozen and I can't even delete them and I have to wait a few hours for them to timeout a rollback transaction.

Anybody is seeing something similar ?

**Comment by KevinRiordan** [comment]
yeah i was seeing the same thing. So I create the device handler then create the device then you get one chance to set the properties BEFORE you make the smartapp. once the smart app was published i was unable to delete or edit ANYTHING. the ST app on my phone would not let me delete smart apps or stop them, and i couldnt change anything in the samsung ide. I made another duplicate and changed the name along the way but was still unable to get it going. 

I too have confirmed that my mbs is running and connected to my mqtt broker but i see nothing from samsung.

**Comment by AlexDanault** [comment]
@KevinRiordan That's interesting, I tried to do it the way you said (configure the ip/port/mac before creating the SmartApp) and you are right, it does work (I can save them) but then I get stuck later when configuring the SmartApp. I can set the bridge device, add switches and other things but I get an error when saving that configuration :(

**Comment by sgupta999** [comment]
Definitely a ST thing. Not sure I can be of much help - call customer service and have them delete these

**Comment by AlexDanault** [comment]
After a few hours you can delete them yourself, they need to timeout.

But @sgupta999  any idea why the MQTT bridge doesn't work for us ?

Thanks !

**Comment by sgupta999** [comment]
Not exactly sure what is not working for you folks. You need to specify the bridge in the SmartApp configuration so absolutely bridge device needs to be created before the SmartApp.

Please provide some info about your environment - are u running on Windows / linux, docker images or shell scripts etc.

I have several detailed documentation about how each set up needs to be configured.

The MAC address of the machine running MBS server is critical for how ST communicates with bridge - and ST is very finicky about how it accomplishes that.

Search older issues - I have provided extensive troubleshooting ideas - maybe they will help 

Please also provide logs from the server and the ST IDE

**Comment by sgupta999** [comment]
There are additional menus from in ST IDE if you select the hub from location to delete IDEs. I have never had issues with deleting MBS SmartApp but have had similar issues that you mention with other third part smart apps. U should be able to change configuration or SmartApp anytime 

There could be something in your environment - Samsung is always vague about why this happens

**Comment by KevinRiordan** [comment]
I am using dockers on a linux machine and alpine 1.03 image. I used the mac
of the ethernet interface of my linux as the mac

**Comment by sgupta999** [comment]
Did you follow the steps as outlined at 
https://github.com/sgupta999/mqtt-bridge-smartthings/blob/master/DOCKER.md

make sure port mappings are correct - this needs to be very carefully done.
On Windows I had to tweak the firewall to allow a specific docker process through.
```
Type: Inbound
Program: C:\Program Files\Docker\Docker\resources\com.docker.backend.exe
Allow all connections
```

I am assuming you have to do something similar in linux  - have you made sure your linux firewall is not blocking.

Took me a while to figure that out.
Of course also make sure you are using MAC of the same NIC for connecting to internet if you have dual NIC or using wifi/wired

Also not sure I understand what you mean by -  you actually cannot save the IPaddress, mac & port for bridge in configuration. nothing here should prevent you from doing that - if you are not able to save IPAddress, mac & port in bridge config that is a completely different issue to do with ST

**Comment by AlexDanault** [comment]
I'd like to update/close this issue now that I have partly resolve the problem(s) I was facing.

First, the "can't edit/save ip/port/mac" resolved itself after a couple of install/uninstall everything in smartthings. It seems there's a mystery delay involved here, the apps/device handler has to stay uninstalled for a few days otherwise smartthings appears to reuse the old ones and you're still locked.

The other issue I was facing (no communications between the hub and the bridge) I found my mistake while digging around: the Device Network ID of the bridge device MUST be set to the MAC of the device running the bridge, in caps, without any separator. So if your bridge is running on a1:b2:c3:d4:e5:f6 then your device network id must be set to A1B2C3D4E5F6 when creating the device in smartthings graph.
