### ISSUE TITLE
MBS-Bridge Device Handler not found

### ISSUE THREAD

**Issue by stofakiller** [sgupta999/mqtt-bridge-smartthings#22]
Hi

I get an 404 when trying MBS-Bridge Device Handler, anywhere else i can find it?

**Comment by stofakiller** [comment]
Found it, but you need to fix the link
https://github.com/sgupta999/mqtt-bridge-smartthings/blob/master/smartapps/gupta/mqtt/mbs-smartapp.src/mbs-smartapp-full.groovy

**Comment by sgupta999** [comment]
not sure what you want me to fix?

**Comment by stofakiller** [comment]
The link to MBS on https://github.com/sgupta999/mqtt-bridge-smartthings, doesnt work
