### ISSUE TITLE
mqtt update

### ISSUE THREAD

**Issue by stofakiller** [sgupta999/mqtt-bridge-smartthings#23]
How can i get en update from a sensor eg 
Xiaomi Temp Sensor or battery status etc... I have from another smartthings/nodered, that i can send a update topic and get a mqtt status

**Comment by sgupta999** [comment]
follow the installation and define the topics and the device ind devices.yml  - please look around the readme and issues - there are several examples.

my whole development environment is corrupted else i could have given you an example

**Comment by stofakiller** [comment]
ok, thanks
