### ISSUE TITLE
Working with WebCore

### ISSUE THREAD

**Issue by rhamblen** [sgupta999/mqtt-bridge-smartthings#4]
Not a bug but a note...
when using webcore, the switches (only tested these) dont show in the main actuator list.
You need to look in the 'Compatibiliy Group 3 -> switches' section.

**Comment by sgupta999** [comment]
Are you talking about the tasmotaswitchsensor and other device types that I created
I guess I could add the actuator capability - anyway atomicState doesnt work for device handlers so still working on updating the device handler - essentially if you are hitting the refresh - sometime you will have to refresh a 2nd time to get all updates synced up.

**Comment by rhamblen** [comment]
they now all appear in the default area like other switches.
