### ISSUE TITLE
enable the wiki...

### ISSUE THREAD

**Issue by rhamblen** [sgupta999/mqtt-bridge-smartthings#9]
can you add me to the authorisation to the wiki...
I want to start using the wiki to provide instructions rather than the readme...
you can navidage the readme, and then you can find you get lost in the information.
The wiki means we can focus on specific instructions and drill into the detail.

https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by sgupta999** [comment]
added you as collaborator to edit wiki

**Comment by rhamblen** [comment]
ive started to populate the basic stuff, will do a custom index later and add some graphics.

**Comment by sgupta999** [comment]
thanks I will edit as needed

**Comment by rhamblen** [comment]
I need to build the side bar
then want to start adding the sections so we explain the content in the devices.yml and also in the smartapp.
then want to explain how to use or build a device handler.

the bridge bit should be the easiest thing to sort... its ensuring people understand the device side and how to connect to smartthings.

ultimately the more device handlers people can build - so we have a library - the better.
that way we can try to change the way smartthings have adopted MQTT and think about a generic bridge rather than just connecting to their own MQTT device.

**Comment by sgupta999** [comment]
Frankly I don’t really think most folks need a custom device handler for basic operation. 

For example if u have a 3 channel switch then u would need to create 3 virtual switches in ST (which u would anyway assuming u want to control them independently) and do the corresponding mapping in the confit file.

So if the device u r using corresponds to a ST simulated device or for that matter any other device handler that can be mapped to any of the field maps in the SmartApp - u don’t need to implement custom device handlers.

It’s for composite devices or building dashboards for multiple devices when u need to build custom but 80/20 rule should not need custom DTH

**Comment by sgupta999** [comment]
If u check my profile I create a new ST device repository -  I am going to move all SmartApp and DTH under MQTT namespace so we can start building tweaks or custom DTH

I just built a “presence sensor” today that basically Pings a d1 or any IP or host and sends an MQTT msg that can now be sent to  ST but in ST I am using the basic simulated ST presence sensor - did not have to create a custom DTH 

Working on building a garage opener that will interface using MQTT - all code is ready just waiting for my contact sensors to arrive so I can test in real life
